# Generated by Django 3.2.1 on 2021-05-04 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pnl', models.FloatField(blank=True, default=0, null=True)),
                ('balance', models.IntegerField(default=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_date', models.DateTimeField()),
                ('sell_date', models.DateTimeField(blank=True, null=True)),
                ('buy_price', models.IntegerField()),
                ('sell_price', models.IntegerField(blank=True, null=True)),
                ('num_units', models.IntegerField(default=1)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks_core.portfolio')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks_core.ticker')),
            ],
        ),
    ]
