# Generated by Django 3.2.1 on 2021-05-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_core', '0002_auto_20210513_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='note',
            field=models.CharField(default='this is a note', max_length=600),
            preserve_default=False,
        ),
    ]
