# Generated by Django 3.2.1 on 2021-05-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_core', '0003_portfolio_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='note',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
