# Generated by Django 3.2.1 on 2021-05-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_core', '0004_alter_portfolio_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='buy_price',
            field=models.DecimalField(decimal_places=3, max_digits=100),
        ),
        migrations.AlterField(
            model_name='position',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=100, null=True),
        ),
    ]
