# Generated by Django 3.2.1 on 2021-05-21 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_core', '0005_auto_20210518_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='currency_code',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticker',
            name='currency_symbol',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticker',
            name='exchange',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='stocks_core.portfolio'),
        ),
    ]
